name: publish

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Test Build
        working-directory: ./demo
        run: |
          cd demo
          npm i
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Dependencies
        working-directory: ./demo
        run: npm i
      - name: Build Project
        working-directory: ./demo
        run: npm run build
      - name: Prepare Project
        working-directory: ./demo
        run: touch build/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: demo/build
